// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	endpoint "github.com/go-kit/kit/endpoint"
	service "github.com/makersu/go-kit-example-string/string/pkg/service"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	UppercaseEndpoint endpoint.Endpoint
	CountEndpoint     endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.StringService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		CountEndpoint:     MakeCountEndpoint(s),
		UppercaseEndpoint: MakeUppercaseEndpoint(s),
	}
	for _, m := range mdw["Uppercase"] {
		eps.UppercaseEndpoint = m(eps.UppercaseEndpoint)
	}
	for _, m := range mdw["Count"] {
		eps.CountEndpoint = m(eps.CountEndpoint)
	}
	return eps
}
